apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voiesbordelaises.fullname" . }}
  labels:
    {{- include "voiesbordelaises.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_MAPBOX_CENTER: "{{ .Values.mapbox.center }}"
  NEXT_PUBLIC_MAPBOX_ZOOM: "{{ .Values.mapbox.zoom }}"
