apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "voiesbordelaises.fullname" . }}
  labels:
    {{- include "voiesbordelaises.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "voiesbordelaises.fullname" . }}
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: voiesbordelaises
